# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - master
    - develop

variables:
    dockerId: stompf
    imageName: lunne-web

jobs:
    - template: templates/build.yml
      parameters:
          ${{ if eq(variables['build.sourceBranch'], 'refs/heads/develop') }}:
              tag: 'beta'
              invokeConnection: 'lunne-web-beta'
          ${{ if eq(variables['build.sourceBranch'], 'refs/heads/master') }}:
              tag: 'latest'
              invokeConnection: 'lunne-web'
