# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
    dockerId: stompf
    imageName: lunne-web

trigger:
    - master
    - develop

jobs:
- job: Build_master
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  steps:
    - script: |
          docker build -t $(dockerId)/$(imageName):latest .
          docker login -u $(dockerId) -p $pswd
          docker push $(dockerId)/$(imageName):latest
      env:
          pswd: $(dockerPassword) 
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'lunne-web'
        method: 'POST'
        
- job: Build_beta
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
  steps:
    - script: |
          docker build -t $(dockerId)/$(imageName):beta .
          docker login -u $(dockerId) -p $pswd
          docker push $(dockerId)/$(imageName):beta
      env:
          pswd: $(dockerPassword) 
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'lunne-web-beta'
        method: 'POST'