parameters:
    tag: ''
    invokeConnection: ''

jobs:
    - job: Build_docker
      pool:
          vmImage: 'Ubuntu-16.04'
      steps:
          - script: |
                echo "building docker image as $(dockerId)/$(imageName):${{ parameters.tag }} using web hook ${{ parameters.invokeConnection }}"
                docker build -t $(dockerId)/$(imageName):${{ parameters.tag }} .
                docker login -u $(dockerId) -p $pswd
                docker push $(dockerId)/$(imageName):${{ parameters.tag }}
            env:
                pswd: $(dockerPassword)

    # - job: Web_hook
    #   pool: 'server'
    #   dependsOn: Build_docker
    #   condition: succeeded('Build_docker')
    #   steps:
    #       - task: InvokeRESTAPI@1
    #         inputs:
    #             connectionType: connectedServiceName
    #             serviceConnection: ${{ parameters.invokeConnection }}
    #             method: 'POST'
